
name: Tape-out closed

on: pull_request_target

jobs:
  Comment_on_PR:
    runs-on: ubuntu-latest
    name: Leave a comment on the Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
#            Thank you for your pull request! :wave:
          message: |
            This fabrication run is closed. Please submit your design in the next fabrication run.  https://github.com/SiEPIC/openEBL-2026-02
          comment_tag: welcome-message

